# Support: https://discord.gg/badbones-s-live-chat-182615261403283459
# Github: https://github.com/Crazy-Crew
#
# Issues: https://github.com/Crazy-Crew/ChatManager/issues
# Features: https://github.com/Crazy-Crew/ChatManager/issues
root:
  # The prefix that appears in front of commands!
  prefix: "<blue>[<gold>ChatManager<blue>] <reset>"
  # This option will tell the plugin to send all messages as action bars or messages in chat.
  #
  # send_message -> sends messages in chat.
  # send_actionbar -> sends messages in actionbar.
  message-action: "send_message"
  # Configuration options related to the plugin database!
  storage:
    # The type of database which we store data in!
    #
    # Available Types:
    #   ⤷ POSTGRESQL
    #   ⤷ SQLITE (DEFAULT)
    #   ⤷ JSON (UNAVAILABLE)
    type: "SQLITE"
    # Define the address and port for the database.
    # - The standard DB engine port is used by default
    #   (MySQL: 3306, PostgreSQL: 5432)
    connection:
      url: "your_ip"
      port: "" # Defaults to default port for database type if empty/removed.
    # The name of the database, which must be created by you.
    database: "your_database"
    # The username for the database.
    username: "your_username"
    # The password for the database.
    password: "your_password"

    # These settings apply to the MySQL connection pool.
    # - The default values will be suitable for the majority of users.
    # - Do not change these settings unless you know what you're doing!
    pool-settings:
      # Sets the maximum size of the MySQL connection pool.
      # - Basically this value will determine the maximum number of actual
      #   connections to the database backend.
      # - More information about determining the size of connection pools can be found here:
      #   https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      maximum-pool-size: 10

      # Sets the minimum number of idle connections that the pool will try to maintain.
      # - For maximum performance and responsiveness to spike demands, it is recommended to not set
      #   this value and instead allow the pool to act as a fixed size connection pool.
      #   (set this value to the same as 'maximum-pool-size')
      minimum-idle: 10

      # This setting controls the maximum lifetime of a connection in the pool in milliseconds.
      # - The value should be at least 30 seconds less than any database or infrastructure imposed
      #   connection time limit.
      maximum-lifetime: 1800000 # 30 minutes

      # This setting controls how frequently the pool will 'ping' a connection in order to prevent it
      # from being timed out by the database or network infrastructure, measured in milliseconds.
      # - The value should be less than maximum-lifetime and greater than 30000 (30 seconds).
      # - Setting the value to zero will disable the keepalive functionality.
      keepalive-time: 0

      # This setting controls the maximum number of milliseconds that the plugin will wait for a
      # connection from the pool, before timing out.
      connection-timeout: 5000 # 5 seconds

  # Settings related to the motd.
  motd:
    # Should the message of the day be sent?
    toggle: false
    # The time to wait in seconds before sending the message of the day.
    delay: 0